### Submit Contact Us Form - Public
POST {{baseUrl}}/contact/submit
Content-Type: application/json

{
    "name" : "Piyush Kumar Raikwar",
    "email" : "piyushraikwar289@gmail.com",
    "phone" : "8817762774",
    "message" : "Hello"
}

### Get all contact us message - Protected
GET {{baseUrl}}/contact/admin
Authorization: Bearer {{token}}
Accept: application/json


### Get single contact us message by id - Protected
GET {{baseUrl}}/contact/admin/68fa0a53cbe18ed52efbaffc
Authorization: Bearer {{token}}
Accept: application/json



### Delete single contact us message by id - Protected
DELETE  {{baseUrl}}/contact/admin/destroy/68fa0a53cbe18ed52efbaffc
Authorization: Bearer {{token}}
Accept: application/json

