
### Get All Active Service - Public
GET {{baseUrl}}/service
Accept: application/json

### Get Service By ID - Public
GET {{baseUrl}}/service/view/68fb66d0fe5e7c3eb4fc9626
Accept: application/json

### Get All Service - Protected
GET {{baseUrl}}/service/admin/all
Authorization: Bearer {{token}}
Accept: application/json


### Delete Service By ID - Protected
DELETE  {{baseUrl}}/service/admin/68fb66d0fe5e7c3eb4fc9626
Authorization: Bearer {{token}}
Accept: application/json