### Get All Testimonials - Protected
GET {{baseUrl}}/testimonial/all
Authorization: Bearer {{token}}
Accept: application/json


### Get All Active Testimonials - Public
GET {{baseUrl}}/testimonial
Accept: application/json


### Get Testimonials By ID - Public
GET {{baseUrl}}/testimonial/68f8ea5e9c46c4fa75e10ed6
Accept: application/json